//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CP22
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contacts
    {
        public int ID { get; set; }
        public int Patient { get; set; }
        public string PhoneNumber { get; set; }
        public string Adres { get; set; }
        public string Email { get; set; }
    
        public virtual Patients Patients { get; set; }
    }
}
