//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CP22
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalHistory
    {
        public int ID { get; set; }
        public int Card { get; set; }
        public int Doctor { get; set; }
        public string Note { get; set; }
        public System.DateTime Datetime { get; set; }
        public byte[] Documents { get; set; }
    
        public virtual MedCards MedCards { get; set; }
        public virtual Users Users { get; set; }
    }
}
