//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CP22
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patients
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patients()
        {
            this.Contacts = new HashSet<Contacts>();
            this.MedCards = new HashSet<MedCards>();
        }
    
        public int ID { get; set; }
        public string FName { get; set; }
        public string SName { get; set; }
        public string LName { get; set; }
        public System.DateTime BurthDay { get; set; }
        public string Sex { get; set; }
        public string Passport { get; set; }
        public bool ParentsPassport { get; set; }
        public string BirthСertificateSeria { get; set; }
        public string BirthCertificateNum { get; set; }
        public string BurthPlase { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public string Policy { get; set; }
        public int PolicyOrg { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contacts> Contacts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedCards> MedCards { get; set; }
        public virtual Policy Policy1 { get; set; }
    }
}
