//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CP22
{
    using System;
    using System.Collections.Generic;
    
    public partial class Policy
    {
        public int IDNumber { get; set; }
        public string BurthPlase { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public string InsuranceOrganization { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public string RepresentativeFN { get; set; }
        public string RepresentativeSN { get; set; }
        public string RepresentativeLN { get; set; }
        public string Adres { get; set; }
    
        public virtual Patients Patients { get; set; }
    }
}
